### ISSUE TITLE
groupBy

### ISSUE THREAD

**Issue by seveves** [surma/underdash#10]
What implementation would you choose for a groupBy function like demanded/described here:
[stackoverflow question](https://stackoverflow.com/questions/14446511/what-is-the-most-efficient-method-to-groupby-on-a-javascript-array-of-objects)

Kind regards and thank you for this collection 👍

**Comment by surma** [comment]
The top answer is very similar to what I wrote a while ago. I don’t think the code is easy to read and I also think it should use a `Map()` because you can‘t guarantee  but it’s not really “nice” code so I chose to not include it.
